<a href="https://colab.research.google.com/github/sachin56432/Text-Preprocessing/blob/main/imdb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [25]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("lakshmi25npathi/imdb-dataset-of-50k-movie-reviews")

print("Path to dataset files:", path)

Using Colab cache for faster access to the 'imdb-dataset-of-50k-movie-reviews' dataset.
Path to dataset files: /kaggle/input/imdb-dataset-of-50k-movie-reviews

In [26]:
import numpy as np
import pandas as pd

In [27]:
temp_df = pd.read_csv('/kaggle/input/imdb-dataset-of-50k-movie-reviews/IMDB Dataset.csv')

In [28]:
df=temp_df.iloc[:10000]

In [29]:
df.head()

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [30]:
df['review'][1]

'A wonderful little production. <br /><br />The filming technique is very unassuming- very old-time-BBC fashion and gives a comforting, and sometimes discomforting, sense of realism to the entire piece. <br /><br />The actors are extremely well chosen- Michael Sheen not only "has got all the polari" but he has all the voices down pat too! You can truly see the seamless editing guided by the references to Williams\' diary entries, not only is it well worth the watching but it is a terrificly written and performed piece. A masterful production about one of the great master\'s of comedy and his life. <br /><br />The realism really comes home with the little things: the fantasy of the guard which, rather than use the traditional \'dream\' techniques remains solid then disappears. It plays on our knowledge and our senses, particularly with the scenes concerning Orton and Halliwell and the sets (particularly of their flat with Halliwell\'s murals decorating every surface) are terribly well done.'

In [31]:
df['sentiment'].value_counts()

sentiment
positive    5028
negative    4972
Name: count, dtype: int64

In [32]:
df.isnull().sum()

review       0
sentiment    0
dtype: int64

In [33]:
print(df.duplicated().sum())

17

In [34]:
df.drop_duplicates(inplace=True)

/tmp/ipykernel_4839/3006716147.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.drop_duplicates(inplace=True)

In [35]:
import re
def remove_tags(raw_text):
  cleaned_text=re.sub(re.compile('<.*?>'),'',raw_text)
  return cleaned_text

In [36]:
df['review']=df['review'].apply(remove_tags)

/tmp/ipykernel_4839/2928534252.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['review']=df['review'].apply(remove_tags)

In [37]:
df['review'][1]

'A wonderful little production. The filming technique is very unassuming- very old-time-BBC fashion and gives a comforting, and sometimes discomforting, sense of realism to the entire piece. The actors are extremely well chosen- Michael Sheen not only "has got all the polari" but he has all the voices down pat too! You can truly see the seamless editing guided by the references to Williams\' diary entries, not only is it well worth the watching but it is a terrificly written and performed piece. A masterful production about one of the great master\'s of comedy and his life. The realism really comes home with the little things: the fantasy of the guard which, rather than use the traditional \'dream\' techniques remains solid then disappears. It plays on our knowledge and our senses, particularly with the scenes concerning Orton and Halliwell and the sets (particularly of their flat with Halliwell\'s murals decorating every surface) are terribly well done.'

In [38]:
df['review']=df['review'].str.lower()

/tmp/ipykernel_4839/514805946.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['review']=df['review'].str.lower()

In [39]:
from nltk.corpus import stopwords
import nltk
nltk.download('stopwords')
sw_list=stopwords.words('english')
def remove_stopwords(text):
  new_text=[]
  for word in text.split():
    if word in sw_list:
      new_text.append('')
    else:
      new_text.append(word)
  return " ".join(new_text)

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

In [40]:
df['review']=df['review'].apply(remove_stopwords)

/tmp/ipykernel_4839/1478176011.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['review']=df['review'].apply(remove_stopwords)

In [41]:
print(df['review'][1])

 wonderful little production.  filming technique   unassuming-  old-time-bbc fashion  gives  comforting,  sometimes discomforting, sense  realism   entire piece.  actors  extremely well chosen- michael sheen   "has got   polari"      voices  pat too!   truly see  seamless editing guided   references  williams' diary entries,     well worth  watching     terrificly written  performed piece.  masterful production  one   great master's  comedy   life.  realism really comes home   little things:  fantasy   guard which, rather  use  traditional 'dream' techniques remains solid  disappears.  plays   knowledge   senses, particularly   scenes concerning orton  halliwell   sets (particularly   flat  halliwell's murals decorating every surface)  terribly well done.

In [42]:
X=df.iloc[:,0:1]
Y=df['sentiment']

In [43]:
X

                                                 review
0     one    reviewers  mentioned   watching  1 oz e...
1      wonderful little production.  filming techniq...
2      thought    wonderful way  spend time    hot s...
3     basically there's  family   little boy (jake) ...
4     petter mattei's "love   time  money"   visuall...
...                                                 ...
9995  fun, entertaining movie  wwii german spy (juli...
9996  give   break.   anyone say     "good hockey mo...
9997   movie   bad movie.   watching  endless series...
9998     movie   probably made  entertain  middle sc...
9999  smashing film  film-making. shows  intense  st...

[9983 rows x 1 columns]

In [44]:
from sklearn.preprocessing import LabelEncoder
encoder=LabelEncoder()
Y=encoder.fit_transform(Y)

In [45]:
Y

array([1, 1, 1, ..., 0, 0, 1])

In [46]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,Y,test_size=0.2,random_state=1)

In [47]:
X_train.shape

(7986, 1)

In [48]:
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer()

In [51]:
X_train_bow=cv.fit_transform(X_train['review']).toarray()
X_test_bow=cv.transform(X_test['review']).toarray()

In [52]:
from sklearn.naive_bayes import GaussianNB
gnb=GaussianNB()
gnb.fit(X_train_bow,y_train)

GaussianNB()

In [53]:
y_pred=gnb.predict(X_test_bow)

In [59]:
from sklearn.metrics import accuracy_score,confusion_matrix
accuracy_score(y_test,y_pred)

0.6324486730095142

In [60]:
confusion_matrix(y_test,y_pred)

array([[717, 235],
       [499, 546]])

In [63]:
from sklearn.ensemble import RandomForestClassifier
rf=RandomForestClassifier()
rf.fit(X_train_bow,y_train)
y_pred=rf.predict(X_test_bow)
accuracy_score(y_test,y_pred)

0.8477716574862293

In [65]:
cv=CountVectorizer(max_features=3000)

x_train_bow=cv.fit_transform(X_train['review']).toarray()
x_test_bow=cv.transform(X_test['review']).toarray()

rf=RandomForestClassifier()
rf.fit(x_train_bow,y_train)
y_pred=rf.predict(x_test_bow)
accuracy_score(y_test,y_pred)

0.829243865798698

In [66]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [67]:
tfidf=TfidfVectorizer()
x_train_tfidf=tfidf.fit_transform(X_train['review']).toarray()
x_test_tfidf=tfidf.transform(X_test['review']).toarray()

In [69]:
rf=RandomForestClassifier()
rf.fit(x_train_tfidf,y_train)
y_pred=rf.predict(x_test_tfidf)
accuracy_score(y_test,y_pred)

0.8392588883324987